# Site settings
title: LaLaLand Photos
baseurl: "/"
first_published: "2017"
owner: Lauren Ferrell
url: "http://lalaland.photos"
email: l@lalaland.photos
description: > 
  Life through my lens
twitter_username: ferrell_io
github_username:  scrthq

# Build settings
markdown: kramdown

# Default front matter
defaults:
  - scope:
      type: posts
    values:
      portfolio: true
      modal: true

permalink: pretty
google_analytics: UA-101420411-3

exclude:
  - README.md
  - node_modules
  - vendor
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - _drafts/
  - LICENSE.md
  - NOTICE.md
  - Planning.md
  - _excludes/

# include:

plugins:
  - jekyll-avatar
  # - jekyll-default-layout
  - jekyll-feed
  # - jekyll-gist
  # - jekyll-optional-front-matter
  - jekyll-paginate
  # - jekyll-readme-index
  # - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-titles-from-headings

social:
  facebook: https://www.facebook.com/theonlylp
  instagram: https://www.instagram.com/laurenpieper/
  twitter: https://twitter.com/ferrell_io
  linkedin-square: https://www.linkedin.com/in/lauren-pieper-909182ab/
  #github: https://github.com/scrthq/VaporShell
  #reddit: https://www.reddit.com/user/scrthq/
  #gratipay: https://gratipay.com/Vaporshell/
  #paypal: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GU6CJMFGVP6ZS
  email: mailto:l@lalaland.photos
  #flickr:
  #youtube-square:
  #spotify:
  #vimeo:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon: