# Site settings
title: LaLaLand Photos
baseurl: "/"
first_published: 2017
owner: Lauren Ferrell
url: "http://lalaland.photos"
email: l@lalaland.photos
description: > 
  Life through my lens
twitter_username: ferrell_io
github_username:  scrthq

# Build settings
markdown: kramdown

# Default front matter
defaults:
  - scope:
      type: posts
    values:
      gallery: false

permalink: /:category/:title
highlighter: rouge
google_analytics: UA-101420411-3

social:
  facebook: https://www.facebook.com/theonlylp
  instagram: https://www.instagram.com/laurenpieper/
  twitter: https://twitter.com/ferrell_io
  linkedin-square: https://www.linkedin.com/in/lauren-pieper-909182ab/
  #github: https://github.com/scrthq/VaporShell
  #reddit: https://www.reddit.com/user/scrthq/
  #gratipay: https://gratipay.com/Vaporshell/
  #paypal: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GU6CJMFGVP6ZS
  email: mailto:l@lalaland.photos
  #flickr:
  #youtube-square:
  #spotify:
  #vimeo:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon: